version: "3.4"

x-common-variables: &common-variables
  ENVIRONMENT: prod

networks:
  iot:
    driver: bridge

services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.11
    volumes:
      - ./mosquitto:/mosquitto/config
      - ~/docker-volumes/mosquitto/data:/mosquitto/data
      - ~/docker-volumes/logs/:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    networks:
      - iot
    user: 1000:123
